config/routes.rb
Rails.application.routes.draw do
  resources :minions
  resources :bookings
  resources :microposts
  resources :users
  get 'static_pages/home'
  get    '/signup',  to: 'users#new'
  get  '/help',    to: 'static_pages#help'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :user
    belongs_to :minion
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        send_booking_mail
        
        format.html { redirect_to @booking, notice: 'A reserva foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'A reserva foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'A reserva foi cancelada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:numberOfWeeks, :user_id, :minion_id)
    end
    
    # Send mail after created a booking
    def send_booking_mail
      @user = User.find(1)
      @minion = User.find(1)
      BookingMailer.with(user: @user, minion: @minion, booking: @booking).booking_success_mail.deliver_now
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.slim
= form_for @booking do |f|
  - if @booking.errors.any?
    #error_explanation
      h2 = "#{pluralize(@booking.errors.count, "error")} prohibited this booking from being saved:"
      ul
        - @booking.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :numberOfWeeks
    = f.number_field :numberOfWeeks
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :minion_id
    = f.number_field :minion_id
  .actions = f.submit

app/views/bookings/edit.html.slim
h1 Editing booking

== render 'form'

=> link_to 'Show', @booking
'|
=< link_to 'Back', bookings_path

app/views/bookings/index.html.slim
h1 Listing bookings

table
  thead
    tr
      th Numberofweeks
      th User
      th Minion
      th
      th
      th

  tbody
    - @bookings.each do |booking|
      tr
        td = booking.numberOfWeeks
        td = booking.user_id
        td = booking.minion_id
        td = link_to 'Show', booking
        td = link_to 'Edit', edit_booking_path(booking)
        td = link_to 'Destroy', booking, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Booking', new_booking_path

app/views/bookings/new.html.slim
h1 New booking

== render 'form'

= link_to 'Back', bookings_path

app/views/bookings/show.html.slim
p#notice = notice

p
  strong Numberofweeks:
  = @booking.numberOfWeeks
p
  strong User:
  = @booking.user_id
p
  strong Minion:
  = @booking.minion_id

=> link_to 'Edit', edit_booking_path(@booking)
'|
=< link_to 'Back', bookings_path