config/routes.rb
Rails.application.routes.draw do
  resources :minions
  resources :bookings
  resources :microposts
  resources :users
  get 'static_pages/home'
  get    '/signup',  to: 'users#new'
  get  '/help',    to: 'static_pages#help'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/minion.rb
class Minion < ApplicationRecord
    has_many :bookings
end

app/controllers/minions_controller.rb
class MinionsController < ApplicationController
  before_action :set_minion, only: [:show, :edit, :update, :destroy]

  # GET /minions
  # GET /minions.json
  def index
    @minions = Minion.all
  end

  # GET /minions/1
  # GET /minions/1.json
  def show
  end

  # GET /minions/new
  def new
    @minion = Minion.new
  end

  # GET /minions/1/edit
  def edit
  end

  # POST /minions
  # POST /minions.json
  def create
    @minion = Minion.new(minion_params)

    respond_to do |format|
      if @minion.save
        format.html { redirect_to @minion, notice: 'Minion was successfully created.' }
        format.json { render :show, status: :created, location: @minion }
      else
        format.html { render :new }
        format.json { render json: @minion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minions/1
  # PATCH/PUT /minions/1.json
  def update
    respond_to do |format|
      if @minion.update(minion_params)
        format.html { redirect_to @minion, notice: 'Minion was successfully updated.' }
        format.json { render :show, status: :ok, location: @minion }
      else
        format.html { render :edit }
        format.json { render json: @minion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minions/1
  # DELETE /minions/1.json
  def destroy
    @minion.destroy
    respond_to do |format|
      format.html { redirect_to minions_url, notice: 'Minion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_minion
      @minion = Minion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def minion_params
      params.require(:minion).permit(:name, :yearsOfService, :skills, :height, :weight, :photoUrl)
    end
end

app/helpers/minions_helper.rb
module MinionsHelper
end

app/views/minions/_form.html.slim
= form_for @minion do |f|
  - if @minion.errors.any?
    #error_explanation
      h2 = "#{pluralize(@minion.errors.count, "error")} prohibited this minion from being saved:"
      ul
        - @minion.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :yearsOfService
    = f.number_field :yearsOfService
  .field
    = f.label :skills
    = f.text_area :skills
  .field
    = f.label :height
    = f.text_field :height
  .field
    = f.label :weight
    = f.number_field :weight
  .field
    = f.label :photoUrl
    = f.text_field :photoUrl
  .actions = f.submit

app/views/minions/edit.html.slim
h1 Editing minion

== render 'form'

=> link_to 'Show', @minion
'|
=< link_to 'Back', minions_path

app/views/minions/index.html.slim
h1 Listing minions

table
  thead
    tr
      th Name
      th Yearsofservice
      th Skills
      th Height
      th Weight
      th
      th
      th

  tbody
    - @minions.each do |minion|
      tr
        td = minion.name
        td = minion.yearsOfService
        td = minion.skills
        td = minion.height
        td = minion.weight
        td = link_to 'Show', minion
        td = link_to 'Edit', edit_minion_path(minion)
        td = link_to 'Destroy', minion, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Minion', new_minion_path

app/views/minions/new.html.slim
h1 New minion

== render 'form'

= link_to 'Back', minions_path

app/views/minions/show.html.slim
p#notice = notice

p
  strong Name:
  = @minion.name
p
  strong Yearsofservice:
  = @minion.yearsOfService
p
  strong Skills:
  = @minion.skills
p
  strong Height:
  = @minion.height
p
  strong Weight:
  = @minion.weight
p
  strong Photourl:
  = @minion.photoUrl

=> link_to 'Edit', edit_minion_path(@minion)
'|
=< link_to 'Back', minions_path